_format_version: "3.0"
_transform: true

services:
  - name: plane-system-service
    host: plane-system
    port: 8081
    protocol: http
    routes:
      - name: plane-system-route
        paths:
          - /plane-system
        strip_path: true
#  - name: go-system
#    host: go-system
#    port: 8082
#    protocol: http
#    routes:
#      - name: go-system-route
#        paths:
#          - /go
#        strip_path: false
plugins:
  - name: rate-limiting
    config:
      second: 60
      hour: 10000
      policy: local
