server:
  port: 8081
spring:
  application:
    name: plane-system
  datasource:
    url: jdbc:mysql://plane-mysql:3306/plane-system?createDatabaseIfNotExist=true
    username: superadmin
    password: plane@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
            format_sql: true
            default_schema: plane-system
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    try-it-out-enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace